server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul9527.com #修改eureka上的默认描述信息！
    prefer-ip-address: true #显示完整的ip地址，而不是localhost

#info配置
info:
  app.name: lws-springcloud
  company.name: blog.luostudy.com

#zuul配置
zuul:
  routes:
    myMap: #自定义map名称 将微服务名称替换
      serviceId: springcloud-provider-dept #key-value
      path: /mydept/**
  #ignored-services: springcloud-provider-dept #忽略某服务名访问路径，或一些服务名访问路径
  ignored-services: "*" #忽略所有的服务名访问路径
  prefix: /luo #设置公共的前缀

